# Generated by Django 3.0.5 on 2020-11-06 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20201104_0406'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255)),
                ('mobile_no', models.IntegerField()),
                ('location', models.TextField()),
                ('category', models.TextField()),
                ('work_hour', models.IntegerField()),
                ('gender_preference', models.TextField(default='none')),
                ('total_people', models.IntegerField()),
                ('house_size', models.CharField(default='no comment', max_length=255)),
                ('budget', models.CharField(max_length=255)),
                ('comment', models.TextField()),
                ('f_name', models.TextField()),
                ('l_name', models.TextField()),
                ('address', models.CharField(max_length=500)),
                ('zipcode', models.IntegerField()),
            ],
        ),
    ]
