# Generated by Django 3.0.5 on 2020-11-11 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='sitter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=200, null=True)),
                ('lname', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=150, null=True)),
                ('password', models.CharField(max_length=100, null=True)),
                ('address1', models.CharField(max_length=150)),
                ('address2', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=150)),
                ('zipc', models.CharField(max_length=150)),
                ('age', models.CharField(max_length=150)),
                ('gender', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=150)),
                ('marital_status', models.CharField(max_length=150)),
                ('language', models.CharField(max_length=150)),
                ('skills', models.CharField(max_length=150)),
                ('anymore', models.CharField(max_length=150)),
                ('pan_card', models.ImageField(blank=True, null=True, upload_to='')),
                ('aadhar', models.ImageField(blank=True, null=True, upload_to='')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
