# Generated by Django 3.0.5 on 2020-11-16 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20201111_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitter',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
