# Generated by Django 3.0.5 on 2020-11-17 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20201117_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitter',
            name='aadhar_card',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='sitter',
            name='pan_card',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
