# Generated by Django 3.0.5 on 2020-11-18 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20201117_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitter',
            name='desc',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='sitter',
            name='rate',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
