# Generated by Django 3.0.5 on 2020-11-18 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_remove_sitter_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitter',
            name='rate',
            field=models.IntegerField(blank=True, max_length=150, null=True),
        ),
    ]
