# Generated by Django 3.0.5 on 2020-11-18 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_sitter_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='sitter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Sitter'),
        ),
    ]
