# Generated by Django 3.0.5 on 2020-11-18 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20201118_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersitter',
            name='sitter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Sitter'),
        ),
    ]
