# Generated by Django 3.0.5 on 2020-11-18 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20201118_2321'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderSitter',
            new_name='OrderBaby',
        ),
        migrations.AlterField(
            model_name='orderbaby',
            name='sitter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Sitter'),
        ),
    ]
