# Generated by Django 3.0.5 on 2020-11-18 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20201118_2323'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderBaby',
        ),
    ]
