# Generated by Django 3.0.5 on 2020-11-18 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_callbaby'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CallBaby',
            new_name='OrderSitter',
        ),
        migrations.AlterField(
            model_name='ordersitter',
            name='sitter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Sitter'),
        ),
    ]
