# Generated by Django 3.0.5 on 2020-11-27 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20201118_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersitter',
            name='sitter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Sitter'),
        ),
        migrations.AlterField(
            model_name='sitter',
            name='address',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='sitter',
            name='city',
            field=models.CharField(max_length=150),
        ),
    ]
